---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: production
  labels:
    name: proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - image: "kumojin.azurecr.io/proxy:v1.0.13"
          name: proxy
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: acs
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: production
spec:
  ports:
    - name: node
      targetPort: 3000
      port: 3000
  selector:
    app: proxy
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: proxy
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
      secretName: proxy-tls
  rules: